### ISSUE TITLE
Question: Does this integrate with Square POS / magreaders?

### ISSUE THREAD

**Issue by teamcoltra** [Xyfir/rich-cow#1]
Your readme doesn't give much detail on how you perform the Square integration.

**Comment by MrXyfir** [comment]
All you do is set your access token and location key from the Square API in your `.env` file for the server. CCashCow then directs the user to Square's own payment form on Square's website where they'll enter in their credit card details. If I understand you correctly then no, the payment process is entirely online, and does not involve physically handling cards.

**Comment by MrXyfir** [comment]
I'll reopen again if needed.
